### ISSUE TITLE
Change namespace to `libarmgpuinfo`

### ISSUE THREAD

**Issue by mattyclarkson** [ARM-software/libGPUInfo#12]
The `libgpuinfo` namespace implies that this is a utility for gathering generic GPU information.

However, this library (currently) exclusively works with ARM GPUs.

Is the intention that this library will work with other GPUs?

Would it make sense to change this library nomenclature be ARM specific?

**Comment by solidpixel** [comment]
Possibly, although it's never been a problem for other similarly named Arm projects in practice. Any evidence that it's actually causing a problem?

**Comment by mattyclarkson** [comment]
No, more of a question. I was looking to add the library to the Bazel Central Registry (BCR). Adding it as `libgpuinfo` might be too generic. The namespace can be patched for the BCR, if they have concerns about naming.

**Comment by bengaineyarm** [comment]
Does the namespace within the library need to match the ID used in bazel? Granted its a bit of friction, but the two don't need to match right?

**Comment by mattyclarkson** [comment]
No, they don't. I can always add the module as `arm-software-libgpuinfo` (bike shedding welcome) and leave it as `libgpuinfo`. If downstream users have an issue they can always [`single_version_override`](https://bazel.build/external/module#single-version_override) to patch the namespace.

**Comment by solidpixel** [comment]
That said, it's a trivial change for users to adjust to, so happy to make it and avoid the messing about. It's not a painful API break on a large API.
