### ISSUE TITLE
Add a stable release archive to GitHub releases.

### ISSUE THREAD

**Issue by mattyclarkson** [ARM-software/libGPUInfo#15]
GitHub allows downloading a archive of the source code for a commit or tag.

This means that an archive for a tag for this project can be downloaded at: https://github.com/ARM-software/libGPUInfo/archive/refs/tags/1.1.0.tar.gz

However, there is no guarantee that the archive has a consistent checksum as described in https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/.

This is an issue for systems that validate the checksum of the downloaded archive such as Bazel: https://blog.bazel.build/2023/02/15/github-archive-checksum.html

Can we add a generated archive to the release assets that is guaranteed to have a consistent checksum, please?

**Comment by solidpixel** [comment]
GitHub reverted that change, so release checksums should now be stable again. Rejecting this one as no longer planned.
