### ISSUE TITLE
Expose core mask property

### ISSUE THREAD

**Issue by solidpixel** [ARM-software/libGPUInfo#7]
The core mask is useful for remote support as it influences e.g. data processing in Streamline.

**Comment by Atekihcan** [comment]
@solidpixel Does this property signify anything in terms of GPU capabilities? Anything that developers can decide based on this?

**Comment by solidpixel** [comment]
Nothing particularly useful for app developers, it's mostly useful for Arm remote support cases to help understand the physical GPU layout.
